<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <Description>An in-memory implementation of Azure Cloud Storage Services (Microsoft.AzureCosmosTable) useful for testing and local development.</Description>
    <Authors>Andrei Fangli</Authors>
    <Copyright>Andrei Fangli</Copyright>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>logo.png</PackageIcon>
    <PackageReleaseNotes>
      * Added InMemoryCloudTable
    </PackageReleaseNotes>
    <PackageTags>stub;azure;storage;memory;in-memory;test</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/Andrei15193/CloudStub.git</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE" Pack="true" PackagePath="" />
    <None Include="..\logo.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos.Table" Version="1.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CloudStub\CloudStub.csproj" />
  </ItemGroup>

</Project>
